lint_js:
  image: git-registry.alfa.sx:4567/alfatraining/docker/node:14.20-alpine3.16
  stage: build
  except:
    - deployment/production
    - deployment/staging
    - master
  script:
    - yarn
    - yarn lint
  cache:
    key: "${CI_COMMIT_REF_NAME}_${CI_BUILD_REF_NAME}"
    paths:
      - npm-packages-offline-cache
  tags:
    - kubernetes

include:
  - project: "alfatraining/spacedeck-deployment"
    ref: master
    file: "deployment.yaml"
