stages:
  - check_js
  - build

lint_js:
  image: git-registry.alfa.sx:4567/alfatraining/docker/node:26.3-alpine3.24
  stage: check_js
  except:
    - deployment/production
    - deployment/staging
    - master
  before_script:
    - npm install --global yarn@1
  script:
    - yarn
    - yarn lint
  cache:
    key: "${CI_COMMIT_REF_NAME}_${CI_BUILD_REF_NAME}"
    paths:
      - npm-packages-offline-cache
  tags:
    - kubernetes

audit_js:
  image: git-registry.alfa.sx:4567/alfatraining/docker/node:26.3-alpine3.24
  stage: check_js
  except:
    - deployment/production
    - deployment/staging
    - master
  allow_failure: true
  before_script:
    - npm install --global yarn@1
  script:
  # checks for packages with high severity security vulnerabilities
  # yarn audit will return a non-zero exit code if any level of vulnerability is matched - exit code greater than 8 is HIGH or CRITICAL
    - yarn
    - /bin/sh -c 'yarn audit --groups "dependencies"; [[ $? -ge 8 ]] && exit 1 || exit 0'
  cache:
    key: "${CI_COMMIT_REF_SLUG}"
    paths:
      - npm-packages-offline-cache
  tags:
    - kubernetes

include:
  - project: "alfatraining/spacedeck-deployment"
    ref: master
    file: "deployment.yaml"
