FROM git-registry.alfa.sx:4567/alfatraining/docker/node:26.3-bookworm-slim

WORKDIR /app

RUN apt-get update -qq \
  && apt-get install -y --no-install-recommends default-mysql-client \
  && rm -rf /var/lib/apt/lists/*

COPY . .

RUN npm install --global yarn@1
RUN npm install --global gulp-cli
RUN npm install --global nodemon
RUN yarn

CMD ["nodemon", "spacedeck.js"]
