version: "2.0"

services:
  spacedeck:
    build: .
    container_name: spacedeck
    depends_on:
      - mysql
      - nats
    ports:
      - "9666:9666"
    volumes:
      - ./storage:/app/storage
      - ./public:/app/public

  mysql:
    image: mysql:5.6
    container_name: "mysql"
    restart: unless-stopped
    ports:
      - 3306:3306
    volumes:
      - ./mysql:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: "root"
      MYSQL_DATABASE: "spacedeck"

  nats:
    image: "nats:2.1"
    container_name: "nats"
    expose:
      - "4222"
    ports:
      - "4222:4222"
      - "8222:8222"
    hostname: nats-server
